# Generated by Django 4.2.10 on 2025-04-22 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chat_api", "0002_userprofile_fullname"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="chat_api.conversation",
            ),
        ),
    ]
